# echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
sudo: required

language: node_js

node_js:
  - node
  - lts/*

install:
  - yarn install

script:
  - yarn run test

services:
  - docker

deploy:
  provider: script
  script: bash docker_push.sh
  on:
    branch: production
