# echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
sudo: required

language: node.js

services:
  - docker

deploy:
  provider: script
  script: bash docker_push.sh
  on:
    branch: production
